### ISSUE TITLE
Pagination not working at brand pages

### ISSUE THREAD

**Issue by groomershop-mt** [magesuite/brand-management#7]
The pagination is not working at brand pages at Magento 2.4.1 - now on each page it's display all products of selected brand.

This could be related with ElasticSuite, but at all other pages/categories it's working:
https://github.com/Smile-SA/elasticsuite/issues/1912
https://github.com/Smile-SA/elasticsuite/issues/1925

**Comment by jtomaszewski** [comment]
Just for more context: same issue appears at our store in categorysearch page as well, so maybe it's not that much related to brand-management module itself.

**Comment by groomershop-mt** [comment]
When we change theme to Lumia at the same shop, then the issue do not occur, so it will be rather related to theme-creativeshop

It could be caused by moving some elements  - in regards to:
https://github.com/Smile-SA/elasticsuite/wiki/FAQ#i-have-problems-with-the-pagination--sorting

**Comment by groomershop-mt** [comment]
The problem is caused by vendor/creativestyle/theme-creativeshop/src/Magento_CatalogSearch/templates/result.phtml file - there should be applied this commit:

https://github.com/magento/magento2/commit/7035daca3f6b47038d120813ec7164b76ac4bc94#diff-7f64b8e3bdbb6406a30a1e53552a0f31dd086e65eaa6455aef7b81b6cf2389fd

We close this ticket, as it's related to theme-creativeshop.
